j0k3r/banditore

- app/AppKernel.php
- app/config/config_prod.yml
- app/config/parameters.yml.dist
- composer.json
- composer.lock
Send fatal & error log to Sentry
Related https://github.com/j0k3r/banditore/issues/13
> Add Sentry

- app/config/config.yml
swarrot.processor.max_messages: will kill the worker after XX messages. It save a lot of memory by restarting them quite often and always avoid losing MySQL connection.
swarrot.processor.retry: will retry 3 times to publish the message if an error occurs
swarrot.processor.new_relic: to long consumer as background job (even if free tier doesn’t allow visualizing background jobs…)
Might fix https://github.com/j0k3r/banditore/issues/25 & https://github.com/j0k3r/banditore/issues/16
> Add processors for consumer

- .travis.yml
- app/config/services.yml
- composer.json
- composer.lock
- phpunit.xml.dist
- src/AppBundle/Consumer/SyncVersions.php
- src/AppBundle/Github/ClientDiscovery.php
- src/AppBundle/Repository/UserRepository.php
- tests/AppBundle/Consumer/SyncVersionsTest.php
- tests/AppBundle/Github/ClientDiscoveryTest.php
Find the best token to use to fetch data to avoid Rate Limit.
The goal is to find the best authenticated method to avoid hitting the Github rate limit.
We first try with the default application authentication (which might work 99% of the time).
And if it fails, we'll try each user until we find one with enough rate limit.
In fact, the more user in database, the bigger chance to never hit the rate limit (this is theorical).
This mostly to handle new users.
When a new user logged in for the first time we need to retrieve all releases/tags of its starred repos and it use a lot (really a lot) of rate limit.
Also:
- switch from Redis extension to Predis (to support RedisMock)
- use unreleased `php-http/cache-plugin` version 1.3.0 (because we can remove the `private` restriction to be able to …
> Add Github Client Discovery

- src/AppBundle/Consumer/SyncStarredRepos.php
- src/AppBundle/Consumer/SyncVersions.php
- src/AppBundle/Github/ClientDiscovery.php
- src/AppBundle/Github/RateLimitTrait.php
Introduce `RateLimitTrait` to retrieve remaining calls for a given client and also catch an eventually error.
Fix https://github.com/j0k3r/banditore/issues/26
> Avoid /rate_limit to generate error

- app/config/services.yml
- src/AppBundle/Consumer/SyncStarredRepos.php
- tests/AppBundle/Consumer/SyncStarredReposTest.php
This will avoid reaching the rate limit too fast when version check is gourmand.
Also, it allow the request to be cached which will speed up sync
Fix https://github.com/j0k3r/banditore/issues/36
> SyncStarredRepos now use Github Client Discovery

- src/AppBundle/Consumer/SyncStarredRepos.php
- src/AppBundle/Consumer/SyncVersions.php
- src/AppBundle/Github/ClientDiscovery.php
- tests/AppBundle/Consumer/SyncStarredReposTest.php
- tests/AppBundle/Consumer/SyncVersionsTest.php
- tests/AppBundle/Github/ClientDiscoveryTest.php
Return false when no client are available and a check on each consumer to be sure the client is defined.
Fix https://github.com/j0k3r/banditore/issues/38
But need updated after merging https://github.com/j0k3r/banditore/pull/48 (to apply same check on the client to `SyncStarredRepos` consumer)
> Avoid exception from client discovery

- app/AppKernel.php
- app/Resources/views/default/_pagination.html.twig
- app/Resources/views/default/dashboard.html.twig
- app/config/config.yml
- composer.json
- composer.lock
- src/AppBundle/Controller/DefaultController.php
- src/AppBundle/Repository/VersionRepository.php
- tests/AppBundle/Controller/DefaultControllerTest.php
- web/css/banditore.css
When user has a lot of releases the dashboard html page is huge and can take several seconds to display.
Using a pagination the dom is smaller so the page loads faster.
> Add pagination instead of 'show more'

- app/config/config.yml
- app/config/services.yml
- src/AppBundle/Consumer/SyncStarredRepos.php
- src/AppBundle/Consumer/SyncVersions.php
- tests/AppBundle/Consumer/SyncStarredReposTest.php
- tests/AppBundle/Consumer/SyncVersionsTest.php
But retrieves it when needed to avoid error when is goes closed (in case of error).
Might fix https://github.com/j0k3r/banditore/issues/40
> Do not inject EntityManager

- app/config/config.yml
- composer.lock
- src/AppBundle/Consumer/SyncStarredRepos.php
- src/AppBundle/Consumer/SyncVersions.php
- src/AppBundle/DataFixtures/ORM/LoadVersionData.php
- tests/AppBundle/Consumer/SyncStarredReposTest.php
- tests/AppBundle/Consumer/SyncVersionsTest.php
For example when there are two tags:
- V1.0.0
- v1.0.0
utf8mb4 from MySQL is case insensitive, so the unique index will fail after the first insertion. To avoid that I check "to be persisted" entities before validating a new one.
Also, https://github.com/j0k3r/banditore/issues/40 should be fixed for good now.
> Fix case insensitive error for some tag 

- src/AppBundle/Consumer/SyncStarredRepos.php
- src/AppBundle/Consumer/SyncVersions.php
- tests/AppBundle/Consumer/SyncStarredReposTest.php
- tests/AppBundle/Consumer/SyncVersionsTest.php
Avoid have too much message handled for nothing:
```
[2017-03-16 11:53:59] app.NOTICE: Consume banditore.sync_versions message {"repo":"bdunogier/MediapartProxy"}
[2017-03-16 11:53:59] app.NOTICE: [0] Check bdunogier/MediapartProxy …
[2017-03-16 11:53:59] app.WARNING: (repo/tags) You have reached GitHub hourly limit! Actual limit is: 5000
[2017-03-16 11:53:59] app.NOTICE: [0]  new versions for bdunogier/MediapartProxy
[2017-03-16 11:53:59] app.NOTICE: Consume banditore.sync_versions message {"repo":"Squirrel/Squirrel.Windows"}
[2017-03-16 11:53:59] app.NOTICE: [0] Check Squirrel/Squirrel.Windows …
[2017-03-16 11:53:59] app.WARNING: (repo/tags) You have reached GitHub hourly limit! Actual limit is: 5000
[2017-03-16 11:53:59] app.NOTICE: [0]  new versions for Squirrel/Squirrel.Windows …
```
> Stop processing messages when rate limit is reached

- .travis.yml
- web/js/banditore.js
All browsers doesn’t handle `document.querySelectorAll` as an array so we can’t use forEach on it.
See: https://css-tricks.com/snippets/javascript/loop-queryselectorall-matches/
Also, on iOS the font awesome elemnt might not be loaded so if we close the alert it hidde the whole page.
> Can’t loop on document.querySelectorAll

- composer.json
- composer.lock
- src/AppBundle/Consumer/SyncStarredRepos.php
- src/AppBundle/Repository/StarRepository.php
- tests/AppBundle/Consumer/SyncStarredReposTest.php
Star sync was based on repo `full_name`
But this value can change during the sync (for example when a repo change its name) so it become inaccurate.
> Fix star sync

- src/AppBundle/Consumer/SyncStarredRepos.php
- tests/AppBundle/Consumer/SyncStarredReposTest.php
Like it was done for the version sync, check that rate limit is ok.
Since the worker will handle XX messages before quiting, the given Github client might have already reached its limit when the message will be processed and then result in that error:
> [2017-03-29 11:45:02] app.ERROR: [Ack] An exception occurred. Message #2 has been nack'ed. {"swarrot_processor":"ack","exception":"[object] (Github\\Exception\\ApiLimitExceedException(code: 0): You have reached GitHub hourly limit! Actual limit is: 5000 at /www/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php:37)"}
> Re-check rate limit for starred repo

- src/AppBundle/Consumer/SyncVersions.php
On really big repos like vim/vim (5k releases!) we need to flush more often than just after fetching all release.
With 5k release, we can’t fetch all of them in one time (because rate limit is 5k). So it must be done in at least 2 pass. And avoid losing no flushed version between each call, we need to flush more often.
> Flush more often to avoid losing version

- src/AppBundle/Github/ClientDiscovery.php
- tests/AppBundle/Github/ClientDiscoveryTest.php
User token is global to all app. We MUST avoid consoming all of it.
So instead of a low thresold, rise it to let user to other stuff with its Github.
Also, rise the application one to avoid error when fetching new version.
> Rise rate limit thresold for user

- src/AppBundle/Controller/DefaultController.php
- tests/AppBundle/Controller/DefaultControllerTest.php
Starred repositories & user information are public so we don’t need to request custom scope.
Fix https://github.com/j0k3r/banditore/issues/73 & Fix https://github.com/j0k3r/banditore/issues/71
> We don’t need scopes for public data

- src/AppBundle/Controller/DefaultController.php
- src/AppBundle/Repository/RepoRepository.php
- src/AppBundle/Repository/VersionRepository.php
- src/AppBundle/Security/GithubAuthenticator.php
**Improve SQL query for stats page**
Use a better query to retrieve repositories with the most releases.
⚡️  Goes from 3s to 100ms. 💨 
**Use same query for RSS & dashboard**
Instead of grouping repo to display only the latest release on the dashboard, use the same query for the RSS which will display all latest releases non-grouping per repo.
This speedup the query and the dashboard display.
⚡️ Goes from 2s to 55ms. 💨
> Improve queries

- README.md
- app/config/config.yml
- app/config/services.yml
- app/config/services_test.yml
- composer.lock
- data/supervisor.conf
- src/AppBundle/Consumer/SyncStarredRepos.php
- src/AppBundle/Consumer/SyncVersions.php
- src/AppBundle/Github/ClientDiscovery.php
- src/AppBundle/PubSubHubbub/Publisher.php
- tests/AppBundle/Consumer/SyncStarredReposTest.php
- tests/AppBundle/Consumer/SyncVersionsTest.php
- tests/AppBundle/Github/ClientDiscoveryTest.php
- Consumer, GitHub, PubSubHubbub & Webfeeds are now autowire too
- ClientDiscovery now return `null` when no client are found. It’s then easier to autowire GitHub client in consumers because we can type client (to GitHub\Client) and use null when no client are found by the ClientDiscovery
Also fix env definition in command
> Add more autowire services

- src/AppBundle/Github/ClientDiscovery.php
Because it's deprecated now.
See https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters
> Update the way to auth on GitHub

- app/config/config_prod.yml
We don't care about them, at least, in production.
> Exclude 404 from log / Sentry

- src/AppBundle/Cache/CustomRedisCachePool.php
- src/AppBundle/Github/ClientDiscovery.php
- tests/AppBundle/Cache/CustomRedisCachePoolTest.php
Instead of storing the whole huge response from GitHub API, we only keep information we need.
It's 10x smaller for some calls.
It'll avoid having a huge Redis database.
Also, don't cache version/release/tag information as we won't query them again in the future. Once the version is saved we don't update it.
> Improve HTTP Cache for GitHub API calls

- composer.json
- composer.lock
Lazy service aren't built-in Symfony like it was on 3.4.
It needs the `symfony/proxy-manager-bridge` (instead of `ocramius/proxy-manager`)
> Re-enable lazy service

- src/MessageHandler/VersionsSyncHandler.php
Because it can sometime be empty or null.
> Ensure message is a string

- .github/workflows/dependabot-automerge-js.yml
Reducing the time consuming of merging deps which shouldn't break the project
> Allow auto merging of Dependabot JS minor or patch
