j0k3r/banditore

.travis.yml
app/config/services.yml
src/AppBundle/Controller/DefaultController.php
src/AppBundle/Webfeeds/Webfeeds.php
src/AppBundle/Webfeeds/WebfeedsWriter.php
tests/AppBundle/Webfeeds/WebfeedsTest.php
tests/AppBundle/Webfeeds/WebfeedsWriterTest.php

https://blog.feedly.com/10-ways-to-optimize-your-feed-for-feedly/

Enable webfeeds to optimize feeds for feedly

---

app/config/parameters.yml.dist
app/config/services.yml
src/AppBundle/Command/CheckNewVersionCommand.php
src/AppBundle/PubSubHubbub/Publisher.php
src/AppBundle/Repository/UserRepository.php
tests/AppBundle/PubSubHubbub/PublisherTest.php

Publish updated feed to https://pubsubhubbub.appspot.com/

Enable Pubsubhubbub after updating feeds

---

src/AppBundle/Command/CheckNewVersionCommand.php

Github doesn’t sort tags by created date or even doesn’t allow us to sort tags at all.
So we need to retrieve all tags to be sure we don’t miss a new one that’ll be in the bottom of the list from repo/tags.
This is the case (at least) of `ampproject/amphtml`.
See http://stackoverflow.com/q/19452244/569101

Retrieve tag from git/refs/tags instead repo/tags

---

app/Resources/views/default/dashboard.html.twig
data/supervisor.conf
src/AppBundle/Controller/DefaultController.php
src/AppBundle/Repository/VersionRepository.php
web/css/banditore.css

- Fix supervisor command (bad `-e` parameter) & missing queue name
- Display alert after logged in (telling about async import)
- Add pre-release label for release

Little improvements

---

app/Resources/TwigBundle/views/Exception/error.html.twig
app/Resources/views/default/dashboard.html.twig

Default and error page

---

app/AppKernel.php
app/Resources/views/default/dashboard.html.twig
app/config/config.yml
app/migrations/Version20170222055642.php
composer.json
composer.lock
src/AppBundle/Consumer/SyncUserRepo.php
src/AppBundle/Controller/DefaultController.php
src/AppBundle/DataFixtures/ORM/LoadRepoData.php
src/AppBundle/Entity/Repo.php
src/AppBundle/Entity/Version.php
src/AppBundle/Repository/VersionRepository.php
tests/AppBundle/Consumer/SyncUserRepoTest.php

- Add a listing of all releases for the logged in user (maybe plan a pagination?) with a custom MySQL index 
- Add RSS header with repo information for each release (fix #11)
The mobile version of that table is kind of ugly. I'll if I can optimize it later.

Some Improvements

---

app/AppKernel.php
app/config/config.yml
app/config/config_prod.yml
app/config/parameters.yml.dist
composer.json
composer.lock

Using the Ekino bundle
Related https://github.com/j0k3r/banditore/issues/13

Add NewRelic support

---

app/config/services.yml
src/AppBundle/Controller/DefaultController.php
src/AppBundle/DataFixtures/ORM/LoadVersionData.php
src/AppBundle/Rss/Generator.php
tests/AppBundle/Controller/DefaultControllerTest.php
tests/AppBundle/Rss/GeneratorTest.php

Move RSS generation from the controller to a dedicated class which is now fully tested.

Add a RSS generator

---

src/AppBundle/Security/GithubAuthenticator.php
tests/AppBundle/Controller/DefaultControllerTest.php
tests/AppBundle/Security/GithubAuthenticatorTest.php

And now user is always updated after a succesfull login. So its information are always up to date in the database.

Test GithubAuthenticator

---

.travis.yml
README.md
composer.json
composer.lock

Add Coveralls

---

.travis.yml
app/Resources/views/default/dashboard.html.twig
app/config/config.yml
app/config/config_prod.yml
composer.json
composer.lock
src/AppBundle/Controller/DefaultController.php
src/AppBundle/Entity/Repo.php
src/AppBundle/Entity/Star.php
src/AppBundle/Entity/User.php
src/AppBundle/Entity/Version.php
src/AppBundle/Repository/VersionRepository.php
src/AppBundle/Security/GithubAuthenticator.php
tests/AppBundle/Security/GithubAuthenticatorTest.php

- Add description as repo title in the dashboard
- Add custom message when user logged in (first time or come back)
- Use APCu instead of APC (and so this extension is now required)
- Use doctrine default_table_options instead of defining these options on every entities

Improvements

---

src/AppBundle/Consumer/SyncVersions.php
tests/AppBundle/Consumer/SyncVersionsTest.php

Fix https://github.com/j0k3r/banditore/issues/22

Remove PGP signature from message

---

src/AppBundle/Command/SyncStarredReposCommand.php
src/AppBundle/Command/SyncVersionsCommand.php
src/AppBundle/Entity/Repo.php
src/AppBundle/Entity/User.php
tests/AppBundle/Consumer/SyncStarredReposTest.php
tests/AppBundle/Consumer/SyncVersionsTest.php

Increase coverage

---

app/Resources/views/base.html.twig
app/Resources/views/default/dashboard.html.twig
composer.lock
web/css/banditore.css

Responsive dashboard

---

app/Resources/views/default/dashboard.html.twig
web/css/banditore.css

- Use a “read more” button
- Add a little FAQ
Might fix https://github.com/j0k3r/banditore/issues/17

Dashboard improvements

---

src/AppBundle/Consumer/SyncVersions.php

Fix https://github.com/j0k3r/banditore/issues/35

Skip repo if we abuse markdown

---

src/AppBundle/Repository/VersionRepository.php

Also increase the size to 20 items
Fix https://github.com/j0k3r/banditore/issues/39

Return all available releases in RSS

---

composer.json
composer.lock
src/AppBundle/Command/SyncStarredReposCommand.php
src/AppBundle/Command/SyncVersionsCommand.php
tests/AppBundle/Command/SyncStarredReposCommandTest.php
tests/AppBundle/Command/SyncVersionsCommandTest.php

Fix https://github.com/j0k3r/banditore/issues/37

Check empty queue before pushing new message

---

app/Resources/views/base.html.twig
app/Resources/views/default/dashboard.html.twig
tests/AppBundle/Controller/DefaultControllerTest.php
web/css/banditore.css
web/js/banditore.js

Set the menu to be responsive.
Fix https://github.com/j0k3r/banditore/issues/41 & https://github.com/j0k3r/banditore/issues/44

Put a responsive menu

---

app/Resources/views/base.html.twig
app/Resources/views/default/stats.html.twig
src/AppBundle/Controller/DefaultController.php
src/AppBundle/Repository/RepoRepository.php
src/AppBundle/Repository/StarRepository.php
src/AppBundle/Repository/UserRepository.php
src/AppBundle/Repository/VersionRepository.php
tests/AppBundle/Controller/DefaultControllerTest.php
web/css/banditore.css

Fix https://github.com/j0k3r/banditore/issues/24

Stats page

---

app/Resources/views/default/dashboard.html.twig
web/css/banditore.css
web/js/banditore.js

Fix https://github.com/j0k3r/banditore/issues/42

Close alert

---

composer.json
composer.lock

Waiting for https://github.com/KnpLabs/php-github-api/pull/536 to merged upstream (or discussed, etc.)

Use my own fork

---

app/Resources/views/base.html.twig
app/Resources/views/default/dashboard.html.twig
tests/AppBundle/Controller/DefaultControllerTest.php
web/css/banditore.css

The RSS link is no more visible
Fix https://github.com/j0k3r/banditore/issues/43

Better RSS link

---

app/migrations/Version20170329095349.php
src/AppBundle/Entity/User.php

For example: @catsoap (hey thanks / sorry for that :sweat_smile: )

Github name can be null

---

web/js/banditore.js

Might fix https://github.com/j0k3r/banditore/issues/68

Fix error when closing alert

---

src/AppBundle/Github/RateLimitTrait.php

Like when an user revoke its token.
Might fix https://github.com/j0k3r/banditore/issues/72

Avoid exception when receiving a bad credential

---

LICENSE

Added license information, according to the information from the `composer.json' file.

Add License Info

---

.travis.yml
LICENSE
composer.json
composer.lock

Improve autoload

---

app/AppKernel.php
app/Resources/views/default/dashboard.html.twig
app/Resources/views/default/stats.html.twig
app/config/config.yml
app/config/services.yml
composer.json
composer.lock
src/AppBundle/DataFixtures/ORM/LoadRepoData.php
src/AppBundle/DataFixtures/ORM/LoadVersionData.php
src/AppBundle/Rss/Generator.php
src/AppBundle/Twig/RepoVersionExtension.php
tests/AppBundle/Controller/DefaultControllerTest.php
tests/AppBundle/Twig/RepoVersionExtensionTest.php

Not really fixing it but use a better tool for that: KnpTimeBundle
Some tag include characters which need to be encoded

Fix time ago & encode tag name

---

.travis.yml
composer.json
composer.lock
phpstan.neon
src/AppBundle/DataFixtures/ORM/LoadVersionData.php
src/AppBundle/Entity/User.php
src/AppBundle/Security/GithubAuthenticator.php

Enable PHPStan

---

.travis.yml
app/config/config.yml
app/config/config_prod.yml
composer.json
composer.lock
phpstan.neon

Sentry 3.0

---

.travis.yml
app/config/config_test.yml
composer.lock

Since Xenial, we need to explicitly tells Travis to start MySQL.

Update deps & fix MySQL in Travis

---

composer.lock
src/AppBundle/Controller/DefaultController.php
src/AppBundle/Repository/VersionRepository.php
tests/AppBundle/Controller/DefaultControllerTest.php

This will allow me to check whenever everything runs fine because I assume if the latest fetched version is more than 2 hours old, something should be wrong.
Also update deps.

Add a status page

---

Makefile
README.md
app/config/parameters.yml.dist
app/config/services.yml
src/AppBundle/Controller/DefaultController.php

So it'll be easier to define it because it might not be the same for everyone.

Move minute interval before alert in parameter

---

app/Resources/views/base.html.twig
app/Resources/views/default/dashboard.html.twig
app/Resources/views/default/index.html.twig
composer.lock
tests/AppBundle/Controller/DefaultControllerTest.php
web/css/banditore.css

Fix https://github.com/j0k3r/banditore/issues/153
Also:
- update deps
- cleanup CSS
What do you think @ad-si?

Fix RSS/Atom typo

---

.travis.yml
README.md
composer.json
composer.lock

Mostly to be able to bump some deps to latest one instead of being stuck in the past.

Jump to PHP 7.2

---

.travis.yml
app/config/config.yml
composer.json
composer.lock

See https://github.com/j0k3r/f43.me/pull/337

Avoid deprecated message by using a new strategy

---

.gitignore
.travis.yml
app/AppKernel.php
composer.json
composer.lock
phpstan.neon
src/AppBundle/Consumer/SyncStarredRepos.php
src/AppBundle/Consumer/SyncVersions.php
src/AppBundle/Controller/DefaultController.php
src/AppBundle/DataFixtures/ORM/LoadStarData.php
src/AppBundle/DataFixtures/ORM/LoadVersionData.php
src/AppBundle/Entity/Star.php
src/AppBundle/Github/RateLimitTrait.php
src/AppBundle/Security/GithubAuthenticator.php
tests/AppBundle/Command/SyncStarredReposCommandTest.php
tests/AppBundle/Command/SyncVersionsCommandTest.php
tests/AppBundle/Consumer/SyncStarredReposTest.php
tests/AppBundle/Consumer/SyncVersionsTest.php
tests/AppBundle/Controller/DefaultControllerTest.php
tests/AppBundle/PubSubHubbub/PublisherTest.php
tests/AppBundle/Rss/GeneratorTest.php
tests/AppBundle/Security/GithubAuthenticatorTest.php

- Replace some deprecated bundle / packages
- Jump to phpstan level 5

Update some package

---

src/AppBundle/Repository/VersionRepository.php
src/AppBundle/Security/GithubAuthenticator.php

Instead of listing all versions, count them. Much much faster.

Faster post logging

---

src/AppBundle/Consumer/SyncVersions.php

Handle repo access blocked

---

app/config/config.yml

Also at the end, I never used it

Remove deprecated newrelic middleware

---

app/Resources/views/default/dashboard.html.twig
app/config/config.yml
app/config/parameters.yml.dist
app/config/services.yml
src/AppBundle/Consumer/SyncStarredRepos.php
src/AppBundle/Controller/DefaultController.php
tests/AppBundle/Consumer/SyncStarredReposTest.php

That notification will be gone once the sync is done OR after 1h, in case sync has some issues.
Fix #46

Add a dashboard notification when starred repo are being sync

---

app/migrations/Version20170329095349.php
app/migrations/Version20180827105910.php
app/migrations/Version20200511062812.php
src/AppBundle/Consumer/SyncStarredRepos.php
src/AppBundle/Entity/User.php
src/AppBundle/Repository/UserRepository.php
tests/AppBundle/Consumer/SyncStarredReposTest.php

Handle user removed from GitHub

---

app/Resources/views/base.html.twig

Nothing important to change.
Also, use fontawesome from Unpkg instead of bootstrapcdn to remove one preconnect meta.

Upgrade to PureCSS 2.0

---

bin/console
composer.json
composer.lock
config/bundles.php
config/packages/security_checker.yaml
config/packages/validator.yaml
config/routes/dev/framework.yaml
phpstan.neon
public/index.php
src/Kernel.php
src/Security/GithubAuthenticator.php
symfony.lock
tests/Controller/DefaultControllerTest.php

Remove (not so much used) Security Checker.

Jump to Symfony 5.0

---

src/MessageHandler/VersionsSyncHandler.php
tests/MessageHandler/VersionsSyncHandlerTest.php

I wasn't aware of such type of tag.
https://developer.github.com/v3/git/blobs/

Handle "blob" tag

---

.env
composer.lock
config/packages/framework.yaml
config/services.yaml
src/Kernel.php
symfony.lock

Update to Symfony 5.1.3

---

.travis.yml
composer.json
composer.lock
phpstan.neon
symfony.lock

Ditch direct dev deps `php-coveralls`

---

.travis.yml
composer.lock

> Internal error: Package "j0k3r/banditore" is not installed
Run PHPStan with --debug option and post the stack trace to:
https://github.com/phpstan/phpstan/issues/new
Following https://github.com/j0k3r/banditore/pull/404
Looks like it's related to Composer 2. Downgrading fix that issue.

Trying to solve the mysterious PHPStan bug

---

.editorconfig
.github/workflows/coding-standards.yml
.github/workflows/continuous-integration.yml

- Properly enable compose cache
- Better name jobs
- Use alpine version of rabbitmq
- change the way to handle coverage (and remove one job)

Change the way to handle coverage

---

.github/workflows/coding-standards.yml
.github/workflows/continuous-integration.yml
composer.lock

Also:
- use `ramsey/composer-install` to handle composer install & cache

Symfony 5.1.9

---

composer.lock
config/packages/prod/monolog.yaml

To avoid having that:
```
-rwxrwxrwx 1 www-data www-data 205G Dec  7 20:19 prod.log
```

Rotate log

---

config/services_test.yaml
tests/Command/SyncStarredReposCommandTest.php
tests/Command/SyncVersionsCommandTest.php
tests/Controller/DefaultControllerTest.php
tests/Github/ClientDiscoveryTest.php
tests/MessageHandler/StarredReposSyncHandlerTest.php
tests/MessageHandler/VersionsSyncHandlerTest.php
tests/Security/GithubAuthenticatorTest.php

Thanks to https://twitter.com/welcoMattic/status/1463810474726895617

Change the way to retrieve services during tests

---

composer.lock
public/css/banditore.css
public/js/banditore.js
src/MessageHandler/VersionsSyncHandler.php

- Unnecessary semicolon
- Variable assignment found within a condition. Did you mean to do a comparison ?
- Unexpected unit (length-zero-no-unit)
- Unexpected duplicate "display" (declaration-block-no-duplicate-properties)

Fix some issues from Codefactor

---

composer.lock
src/Repository/VersionRepository.php

Following https://github.com/j0k3r/banditore/pull/862 which disable Redis cache for Doctrine, the default one was failing.

Fix error with Doctrine cache
